### ISSUE TITLE
Can't find Authentication string required for stats.i2p in the 'eepsite' tab

### ISSUE THREAD

**Issue by Microcockwinblows** [knaccc/i2p-zero#11]
I can't seem to find where the Authentication string is stored I've looked in the eepsite tab and in the .i2p-zero folder in the users directory and it is not there either is it even possible to get it?

**Comment by knaccc** [comment]
I assume this is so you can register a .i2p domain? The code for generating the signing keys required to create the auth string looks pretty complicated, so it's unlikely to be something we'll be able to figure out in the near future. Thanks for pointing out this feature is missing, I agree it'd be useful for people to generate it for their eepsite.

**Comment by Microcockwinblows** [comment]
Yes it is for registering a i2p domain anyways thanks for the reply
