### ISSUE TITLE
client.create appears to have no effect

### ISSUE THREAD

**Issue by kevcrumb** [knaccc/i2p-zero#15]
Maybe I got the syntax wrong, but I cannot create a client-tunnel. The command doesn't generate any output.

(Whereas http-tunnel works, and returns "OK".)

    # ./tunnel-control.sh router.reachability
    Firewalled
    
    # ./tunnel-control.sh all.list | jq
    {
      "tunnels": []
    }
    
    # ./tunnel-control.sh http.create 4444
    OK
    # ./tunnel-control.sh all.list | jq
    {
      "tunnels": [
        {
          "port": "4444",
          "state": "opening",
          "type": "http"
        }
      ]
    }
    
    # ./tunnel-control.sh client.create 7662 pop.postman.i2p
    # ./tunnel-control.sh all.list | jq
    {
      "tunnels": [
        {
          "port": "4444",
          "state": "opening",
          "type": "http"
        }
      ]
    }

**Comment by kevcrumb** [comment]
Also, I wonder how to provide the destination port. For comparison, here's what the configuration looked like back in kovri-times:

    [PostmanPOP3]
    type = client
    port = 7662
    dest = pop.postman.i2p
    dest_port = 110

**Comment by knaccc** [comment]
As far as I know, I2P destinations don't have ports.

The example you gave will invoke I2P with the following arguments:

`-die -nocli -e config localhost 7654 -e client 7662 pop.postman.i2p`

If this isn't working, perhaps you can find an exception in your ~/.i2p-zero/i2p.config/wrapper.log file. Please monitor that file, invoke the client.create command, and let us know if you see an exception appear at that exact moment. It could be that pop.postman.i2p is not stored in an address book, meaning it cannot be resolved.

**Comment by kevcrumb** [comment]
`./tunnel-control.sh client.create 7662 pop.postman.i2p` caused this in **wrapper.log**:

    java.lang.NumberFormatException: For input string: "pop.postman.i2p"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
        at java.base/java.lang.Integer.parseInt(Integer.java:658)
        at java.base/java.lang.Integer.parseInt(Integer.java:776)
        at org.getmonero.i2p.zero/org.getmonero.i2p.zero.TunnelControl.run(TunnelControl.java:536)
        at java.base/java.lang.Thread.run(Thread.java:835)

So I fed it a number instead: `./tunnel-control.sh client.create 7662 110 pop.postman.i2p`

    New I2CP settings: localhost 7654 non-SSL
    Warning - Could not resolve 7662, you must add it to your address book for it to work.
    Tunnels ready for client: Standard client on 127.0.0.1:110
    Error listening for connections on /127.0.0.1 port 110: java.net.BindException: Permission denied (Bind failed)
    Stopping client 110 -> 7662
    Client error for 127.0.0.1:110, check logs
    Tunnels ready for client: HTTP Proxy on 127.0.0.1:4444
    Client ready, listening on 127.0.0.1:4444

Okay, that was bad. I rather give you the high port for the local side:
`./tunnel-control.sh client.create 110 7662 pop.postman.i2p`

    New I2CP settings: localhost 7654 non-SSL
    Warning - Could not resolve 110, you must add it to your address book for it to work.
    Tunnels ready for client: Standard client on 127.0.0.1:7662
    Client ready, listening on 127.0.0.1:7662

There we go! All nice and shiny.

    # ./tunnel-control.sh all.list | jq '.tunnels[1]'
    {
      "port": "7662",
      "state": "open",
      "type": "client",
      "dest": "110"
    }

I'll check if the tunnel actually works for email and get back.

**Comment by kevcrumb** [comment]
... only that `dest` probably isn't actually the destination port. Noticed the warning just now ...

**Comment by kevcrumb** [comment]
Result: Both of the following cause POP email retrieval to work.

`./tunnel-control.sh client.create pop.postman.i2p 7662`
`./tunnel-control.sh client.create pop.postman.i2p:110 7662`

**Comment by knaccc** [comment]
It was my mistake, the port and dest in the README were written the wrong way around. I've just corrected it. It should have said:

`tunnel-control.sh client.create <I2P destination> <local port>`

This explains why you got it to work when you swapped the parameters around. 

Thanks for pointing this out, and sorry for the confusion.
