### ISSUE TITLE
Route out through a socks server?

### ISSUE THREAD

**Issue by kevcrumb** [knaccc/i2p-zero#16]
Can i2p-zero be configured to **use** a third party socks server to get out into the Internet?

(not talking about i2p-zero **providing** one)

**Comment by knaccc** [comment]
Interesting question, I'm not sure. I don't have a SOCKS server to test with, but perhaps you can try this and let us know if it works:

There is a file called `dist/linux/router/bin/launch.sh` (or `dist/mac/router/bin/launch.sh`)

Edit it to change the following line from:

`"$basedir"/bin/java -cp "$basedir/i2p.base/jbigi.jar" -m org.getmonero.i2p.zero`

to:

`"$basedir"/bin/java -DsocksProxyHost=socks.example.com -cp "$basedir/i2p.base/jbigi.jar" -m org.getmonero.i2p.zero`

You can also set these additional system properties using multiple -Doptionname=value arguments:

> SOCKS
> This is another type of proxy. It allows for lower level type of tunneling since it works at the TCP level. In effect, in the Java(tm) platform setting a SOCKS proxy server will result in all TCP connections to go through that proxy, unless other proxies are specified. If SOCKS is supported by a Java SE implementation, the following properties will be used:
> 
> socksProxyHost (default: <none>)
> The hostname, or address, of the proxy server.
> 
> socksProxyPort (default: 1080)
> The port number of the proxy server.
> 
> socksProxyVersion (default: 5)
> The version of the SOCKS protocol supported by the server. The default is 5 indicating SOCKS V5, alternatively 4 can be specified for SOCKS V4. Setting the property to values other than these leads to unspecified behavior.
> 
> java.net.socks.username (default: <none>)
> Username to use if the SOCKSv5 server asks for authentication and no java.net.Authenticator instance was found.
> 
> java.net.socks.password (default: <none>)
> Password to use if the SOCKSv5 server asks for authentication and no java.net.Authenticator instance was found.
Source: https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html

**Comment by kevcrumb** [comment]
After a long wait in `Testing` is goes to this:

    # ./tunnel-control.sh router.reachability
    ERR-No Active Peers, Check Network Connection and Firewall

Traffic is going out, but nothing in:

    # ./tunnel-control.sh router.getBandwidthStats | tr ',' '\n' | sort
    1sRateInKBps=0.0
    1sRateOutKBps=0.7199122905731201
    5mRateInKBps=0.0
    5mRateOutKBps=0.0
    avgRateInKBps=0.0
    avgRateOutKBps=0.6103515625
    totalInMB=0.0
    totalOutMB=0.16406536102294922

wrapper.log:

    I2P router now running
    New I2CP settings: localhost 7654 non-SSL
    New I2CP settings: localhost 7654 non-SSL
    INFO: Native CPUID library libjcpuid-x86-linux.so loaded from resource
    INFO: Resource name [libjbigi-linux-coreibwl_64.so] was not found
    INFO: Resource name [libjbigi-linux-coreibwl.so] was not found
    INFO: Loaded library: jar:file:/home/kevcrumb/i2p-zero-linux-gui.v1.7/router/runtime/i2p.base/jbigi.jar!/libjbigi-linux-coreihwl_64.so
    INFO: Native BigInteger library libjbigi-linux-coreihwl_64.so loaded from resource
    Tunnels ready for client: Standard client on 127.0.0.1:7662
    Unable to build tunnels for the client, retrying in 20 seconds
    Client ready, listening on 127.0.0.1:7662
    Warning - No client config file /home/kevcrumb/.i2p-zero/config/clients.config
    Warning - No client apps or router console configured - we are just a router
    Warning: Unable to reach any of the NTP servers [0.us.pool.ntp.org, 1.us.pool.ntp.org, 2.us.pool.ntp.org, 0.north-america.pool.ntp.org, 1.north-america.pool.ntp.org, 2.north-
    america.pool.ntp.org, 0.pool.ntp.org, 1.pool.ntp.org, 2.pool.ntp.org] - network disconnected? Or set time.sntpServerList=myserver1.com,myserver2.com in advanced configuration.


I could successfully work around the last warning with `echo 'time.disabled=true' >> ~/.i2p-zero/config/router.config`, but it's a good indicator to see if things are working.

DNS is working flawlessly - verified with `drill 0.us.pool.ntp.org`.

To me, it seems the socks-related switches are ignored altogether. If that's not it, maybe i2p needs UDP where it's not available (?)

**Comment by knaccc** [comment]
I think this might be a good question for the main I2P project. Note that I2P-zero is just a simple wrapper over the official I2P release, so this is really an I2P question more than it is an I2P-zero question.

**Comment by knaccc** [comment]
dr|z3d on irc has confirmed that running I2P over socks or proxies is not possible, unfortunately
