### ISSUE TITLE
Possible to have one identity per connected client?

### ISSUE THREAD

**Issue by kevcrumb** [knaccc/i2p-zero#17]
Copying over from IRC:

I was thinking about creating a Dockerfile in order to deploy it as a stand-alone router (interest?), but there's an issue:

Any instance has its unique identifier (the destination public key). So if more than one user routes through that instance, we know that *all* of them are coming from that same router.

Say a household shares the i2p-router. If one of the users would compromise his identity, all the others would have theirs compromised too.

For comparison: Tor automatically creates a new route for every connected client. Additionally, it has an option to get a new route per connection explicitly (e.g. through the `--isolate` switch to the torsocks-command).

Do you see how i2p-zero could do that too?

Maybe one i2p instance is meant to represent one user, but it would allow for some interesting setups if it were possible.

**Comment by knaccc** [comment]
Nice idea, and a very interesting question. I'm not familiar enough with I2P to give an answer on this. In fact, I'm not all that familiar with I2P at all - this project is just a wrapper and build script. I recommend you ask this in the I2P forums or in their IRC channels.

**Comment by kevcrumb** [comment]
Understood. Quick question anyway: Could [SAM (Simple Anonymous Messaging)](https://geti2p.net/en/docs/api/samv3) be what I am looking for?

**Comment by knaccc** [comment]
SAM is just a simple way to talk to a local I2P node, instead of using the lower-level I2CP API.
