### ISSUE TITLE
backup & restore

### ISSUE THREAD

**Issue by szh7379** [knaccc/i2p-zero#20]
How to backup server key and restore it, i did not found any dat file in root and appdata dir?
Just backup the whole appdata dir? how could i use an existed key to creat the same b32 address server tunnel?

**Comment by knaccc** [comment]
You can find it in .i2p-zero/config/tunnels.json

**Comment by szh7379** [comment]
I had checked that, but it is not Base64, not compatible with i2p, how to convert it? i can restore tunnel created in i2p-zero, but i can't restore a tunnel from an existed dat file.

**Comment by knaccc** [comment]
The format is: keypair: base64 secret key, base64 public key. There is also the base32 destination address supplied. If you're trying to use this information outside of I2P-zero, then perhaps you could tell me what format you need it in.

**Comment by szh7379** [comment]
I don't know the key's format very much, everytime reinstall, i just use the *.dat file to overwrite the new generated key. it contain some signaturetypes, if i2p-zero use an unified signaturetype, it may not be converted to a secret key. even we can, need to convert all keys, it is not convenient to migrate i2p to i2p-zero.

**Comment by jtgrassie** [comment]
.dat files, as used by i2p, store the keys in the format described [here](https://github.com/i2p/i2p.i2p/blob/973aab8f53e3eaf52f51459bdbe2d3d9a2e5e51b/core/java/src/net/i2p/data/PrivateKeyFile.java#L38).

If the goal is to backup the keys created by i2p-zero, just backup ` .i2p-zero/config/tunnels.json` file as @knaccc described. This just base64 encodes the keys in the json file. If you really needed those keys in the format used by the full i2p application, it is fairly easy to convert those keys to the dat format described in the link above. E.g. base64 decode the `keypair` field and write 3 nulls after.

**Comment by szh7379** [comment]
Migrate to i2p-zero just because it use too much time to initialize i2p, still think it is not convenient, meybe i2p-zero use the .dat file as tunnel secret key is better.

**Comment by jtgrassie** [comment]
If the goal was config interoperability between the full i2p and i2p-zero, yes, using the dat file would be more sensible. However, the goal is not seamless interoperability of the config files. Having all the tunnel information in one file (the json file), is convenient for i2p-zero.  This said, if we want to provide a seamless switch for users currently using the full i2p to i2p-zero, yes, adding support for reading the dat files could be useful - though we'd need a lot more plumbing so as to know *what* tunnel to create for a given dat file.
