### ISSUE TITLE
Socks port state stays on "opening"

### ISSUE THREAD

**Issue by sanderfoobar** [knaccc/i2p-zero#22]
On Linux, Ubuntu 18.04, the `state` of a socks tunnel will stay on `opening` forever.

**Comment by knaccc** [comment]
The problem appears to be related to the instantiation of the socks I2PTunnel never completing, which must be due to a recent change in the I2P codebase. I'm currently contacting the I2P devs to ask about this.

**Comment by knaccc** [comment]
Fixed in v1.10

**Comment by jtgrassie** [comment]
I'm seeing this too with current master, fresh build, fresh ~/.i2p-zero dir. Stays "opening". No pertinent log in ~/.i2p-zero/config/wrapper.log

**Comment by knaccc** [comment]
As per IRC conversation, this was probably simply because I2P had not warmed up yet, since that takes 5 minutes. I2P-zero is now logging to stdout when I2P has warmed up
