### ISSUE TITLE
GUI - Total transferred cuts off

### ISSUE THREAD

**Issue by dginovker** [knaccc/i2p-zero#25]
![image](https://user-images.githubusercontent.com/32943174/67762424-c785b380-fa1b-11e9-9bc6-0bd0ccc13c07.png)

Could the units maybe change to MB/GB/TB as the digits start growing larger and larger?

**Comment by knaccc** [comment]
Good idea, will do this for the next version

**Comment by dginovker** [comment]
> Good idea, will do this for the next version

On a similar note, can you also make the max bandwidth slider logarithmic?

**Comment by knaccc** [comment]
>  On a similar note, can you also make the max bandwidth slider logarithmic?

I2P maxes out at below 17 MBps, so we thought it would be redundant to offer anything above this level. The built-in slider widget doesn't support logarithmic units, so we'd have to build a new slider from scratch, which would be a bit excessive.
