### ISSUE TITLE
Allow copying of information in the tunnels screen

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [knaccc/i2p-zero#26]
On Windows, I would like to be able to copy important information, especially the i2p address, in the tunnels interface. Additionally, it would be nice to provide an edit option to review and other information, such as the port number.

**Comment by knaccc** [comment]
Cell copying now implemented, will go live in next release.

**Comment by knaccc** [comment]
Tunnel editing now implemented, will go live in next release. I2P may have issues when tunnels are suddenly destroyed and recreated using the same local ports, so some testing will be required. The edit feature is very useful for accessing private keys for existing server tunnels.

**Comment by knaccc** [comment]
Now live in latest v1.18 release.
