### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by danrobi11** [knaccc/i2p-zero#27]
Hello
Im a non-technical noob that been around i2p for a few months now.
I just saw i2p-zero. Heres my feedback
Really light, simple non-technical version of i2p, I love it alot.
Although, since this version is obviously toward non-technical users Its lacking a bit about instruction/info around tunnel and eepsite.
However, best user-friendly version of i2p that I've seeing for so far, congrats!
Note: IRC channel?

**Comment by knaccc** [comment]
Thanks, we're on #i2p-zero on freenode.
