### ISSUE TITLE
Which router config settings are supported? Is it possible to use router families?

### ISSUE THREAD

**Issue by eyedeekay** [knaccc/i2p-zero#30]
I am interested in deploying i2p-zero routers which all share the same router family. I don't see anything for it in the GUI. Is it possible to use router.config style options to use families in i2p-zero? In general, it's not quite clear to me to what extent the I2P configuration from the Java reference implementation applies to i2p-zero, knowing that would be very helpful for some people.

**Comment by knaccc** [comment]
@eyedeekay i2p-zero is exactly the same as i2p, so you can treat it as being identical when it comes to the configuration files. i2p-zero only adds easier tunnel configuration. Nice presentation yesterday, btw.

**Comment by eyedeekay** [comment]
Thanks. :) I'm going to write up a guide for how to do it with the router.config files and blog about it. Closing since my question is answered.
