### ISSUE TITLE
Appears to require JVM when running the launcher?

### ISSUE THREAD

**Issue by nurviro** [knaccc/i2p-zero#37]
Hello. After finishing a reproducible build using Ubuntu in Docker per the readme, I attempted running the launcher and got this error:

```bash
$ ./router/bin/i2p-zero 
Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.
```

I was under the impression from the readme that a minimal JVM gets bundled with the launcher, so am now confused. Is the user required to have their own JVM installed in order to run this?

**Comment by knaccc** [comment]
I just tested this on Mac and Ubuntu, and it works for me in both cases. I built from scratch using docker. The JVM is self-contained as part of the i2p-zero executable, but it does require the .so files which should also be bundled and located in the /router/lib/runtime directory.

```bash
containerId=$(docker run -td --rm ubuntu)
docker cp i2p-zero-linux.v1.20.zip $containerId:/
docker exec -ti $containerId bash
apt-get update
apt-get install unzip
unzip i2p-zero-linux.v1.20.zip
i2p-zero-linux.v1.20/router/bin/i2p-zero
#I2P router launched. Note that it will take several minutes for I2P to warm up before it is ready.
```

**Comment by nurviro** [comment]
I was just able to run it fine using ubuntu / docker. I also just tried it using arch linux within docker and that worked fine. So it seems it just doesn't work on my normal arch install. I'll close this for now since it seems to be something weird with my environment, thank you for the help.
